services:
  - type: web
    name: ca-gl-proceedings-search
    runtime: python
    plan: free
    buildCommand: "python3 scripts/build_db.py"
    startCommand: "python3 webapp.py"
    envVars:
      - key: PDF_BASE_URL
        sync: false
